#! /usr/bin/python

# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

sum = 0

curr_fib = 1
prev_fib = 1

while curr_fib < 4000000 :
  next_fib = curr_fib + prev_fib
  if curr_fib % 2 == 0:
    sum += curr_fib
  prev_fib = curr_fib
  curr_fib = next_fib

print sum
    
    