#
# The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first 
# ten terms would be:
#
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#
#     1: 1
#     3: 1,3
#     6: 1,2,3,6
#    10: 1,2,5,10
#    15: 1,3,5,15
#    21: 1,3,7,21
#    28: 1,2,4,7,14,28
#
# We can see that 28 is the first triangle number to have over five divisors.
#
# What is the value of the first triangle number to have over five hundred 
# divisors?

from math import sqrt
from math import floor

def n_divisors (x):
  count = 0
  root = int(floor(sqrt(x)))
  for i in range (1, root + 1):
#    print i
    if x % i == 0:
      count += 1
  return count * 2

tnum = 1
natural_num = 2
nd = n_divisors(tnum)
while (nd <= 500):
  print nd, tnum, natural_num
  tnum += natural_num
  natural_num += 1
  nd = n_divisors(tnum)
  
  
print tnum, n_divisors(tnum)